<?php

/**
 * @file
 * Primary module hooks for SMPL Base module.
 */

/**
 * Implements hook_page_attachments().
 */
function smpl_base_page_attachments(array &$attachments) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  $current_route = \Drupal::routeMatch()->getRouteName();
  if ($theme === 'gin') {
    $attachments['#attached']['library'][] = 'smpl_theme/admin.overrides';
  }
}
