<?php

/**
 * @file
 * Primary module hooks for SMPL Base module.
 */

/**
 * Implements hook_page_attachments().
 */
function smpl_base_page_attachments(array &$attachments) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  $user = \Drupal::currentUser();

  // Check for theme or permission for the admin menu.
  if ($theme === 'gin' || $user->hasPermission('access administration menu')) {
    $attachments['#attached']['library'][] = 'smpl_theme/admin.overrides';
  }
}
